name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  # deploy:
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Debug event
    #     run: echo "Event: ${{ github.event_name }}"
    #   - uses: actions/setup-node@v4
    #     with:
    #       node-version: '20.x'
    #       registry-url: 'https://npm.pkg.github.com'
    #       # Defaults to the user or organization that owns the workflow file
    #       scope: '@arapucajs'
    #   - name: Install dependencies
    #     run: npm ci
    #   - name: Build
    #     run: npm run build
    #   - name: Bump version (if needed)
    #     id: bump_version
    #     run: |
    #       CURRENT_VERSION=$(node -p "require('./package.json').version")
    #       TAG_VERSION=${GITHUB_REF#refs/tags/v}
    #       echo "Current version: $CURRENT_VERSION"
    #       echo "Tag version: $TAG_VERSION"
    #       if [ "$CURRENT_VERSION" != "$TAG_VERSION" ]; then
    #         echo "Versions differ. Bumping version to $TAG_VERSION"
    #         npm version $TAG_VERSION --no-git-tag-version
    #         echo "Version bumped to $(node -p "require('./package.json').version")"
    #         echo "version_bumped=true" >> $GITHUB_OUTPUT
    #       else
    #         echo "Versions match. No version bump needed."
    #         echo "version_bumped=false" >> $GITHUB_OUTPUT
    #       fi
    #   - name: Publish package
    #     run: npm publish --access public
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     if: steps.bump_version.outputs.version_bumped == 'true'
  gh-pkg-deploy:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@arapucajs'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  npm-deploy:
    name: Publish to npm
    needs: gh-pkg-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
